### PR TITLE
Return smaller slices when compressing

### LINKED ISSUE #21: With nil input slice, the resulting slice has capacity of the input
I have investigated a memory leak in my application; I traced the culprit here.

It seems that after compression, the resulting slice has capacity of the original data; so, if you retain the byte slice as-is, the memory of the size of the original is still held in memory.

That doesn't seem ideal and I don't think why would you want this.

It's fixable by simple `compressed = append([]byte{}, compressed...)` after compression. That takes some time because of the allocation and copy, but will save you a lot of memory.

### PR DESCRIPTION
**Pull request by karelbilek**
Fixes #21

Note that it does NOT do that when user presents a slice, only when the slice is nil.

### CODE REVIEW

**Comment by 4kills** [comment]
@karelbilek Thank you very much for the contribution! 
I am sorry for replying so late but I was very busy the past few weeks. 
I really like your solution and there is indeed no reason as to why one should keep the large slice aside the overhead of allocating and copying the array. However, if efficiency is way more important than memory, the user can still provide a slice to accept that trade-off. I previously worked with only very small packets of compressed data so I didn't notice the memory issue. Thank you for finding and fixing it. 

However, I have one request: I suggest replacing
```go
out = append([]byte{}, out[:n]...)
```
with something like this:
```go
outSmallCap := make([]byte, len(out))
copy(outSmallCap, out)
```
I believe the `make` + `copy` operation will be generally more efficient as it does not need to grow the slice repeatedly. 

To my knowledge (please mention if I am wrong), when using `append`, the new slice will be grown repeatedly, therefore incurring many allocations and internal copies. Additionally, you might end up with a capacity that is twice the size of `len(out)` due to the growing process.  
Meanwhile, `make` only requires one allocation and fits the required buffer exactly (`len(out) == cap(outSmallCap)`), followed by `copy` only occurring one time. 

If you adjust this, I will merge the PR! 

Thank you again for bringing this up and fixing it.

**Comment by karelbilek** [comment]
No problem.

I believe there is an optimization for this case in go compiler for some time, so it doesn't grow repeatedly; but it's better to do it more explicitly, sure.

**Comment by 4kills** [comment]
Okay thank you for letting me know. I didn't know about this optimization.

**Comment by karelbilek** [comment]
reading more/benchmarking seems that I was in error. Append is not repeatedly resizing (it's smarter than that), but make+copy is still optimized better and faster, even when it's a very small different. So I will use it here.

**Comment by 4kills** [comment]
Thank you very much for your contribution and especially for reading up about append vs make+copy. Merging.

**Pull request merged**
